### PR TITLE
Wording

### PR DESCRIPTION
**Pull request by adrianleh**
Removed travel rembs from front page so we don't advertise it too much

### CODE REVIEW

**Comment by MaximilianFranz** [comment]
Agreed!

**Comment by jundl77** [comment]
We need travel reimbursements

**Review by jundl77 — CHANGES_REQUESTED** [review]
Please keep travel reimb. on index

**Review by jundl77 — APPROVED** [review]

**Comment by MaximilianFranz** [comment]
Not agreed

**Comment by LeanderK** [comment]
Let's move the discussion into slack 😉

**Comment by adrianleh** [comment]
Can we now merge this? @jundl77 @LeanderK @MaximilianFranz

**Pull request merged**
