### PR TITLE
rewrote visitors section

### PR DESCRIPTION
**Pull request by LeanderK**
i don't know whether the text is good or the content desirable. I just wrote whatever came to my mind.

### CODE REVIEW

**Comment by adrianleh** [comment]
Looking good! Just reworded a few things here and there

**Comment by adrianleh** [comment]
If there are no further concerns, we could merge it soon

**Comment by LeanderK** [comment]
@jundl77 you weren't exactly blown away 😉 I am also not super convinced but don't see any obvious ways to make it more interesting.

**Comment by jundl77** [comment]
Merge it haha, I don't have time to look over it right now, but I'll improve it in the coming days

**Comment by LeanderK** [comment]
I wouldn't focus too much on the visitor's page, it doesn't get many clicks.

**Pull request merged**
